version: 2
build:
   os: "ubuntu-22.04"
   tools:
      python: "3.10"
   jobs:
      post_install:
         # Install hatch
         - pip install hatch
         # Install dependencies for documentation
         - hatch env create docs
         # Export and install the dependencies
         - hatch --env docs dep show requirements > docs-requirements.txt
         - pip install -r docs-requirements.txt
         # Install the package itself in development mode
         - pip install -e .
sphinx:
   configuration: docs/source/conf.py